birthday1 = input("Enter Joe's birthday in dd/mm/yyyy format:")
birthday2 = input("Enter Ben's birthday in dd/mm/yyyy format:")
birthday3 = input("Enter Rishi's birthday in dd/mm/yyyy format:")
print("Joe's birthday is on",birthday1)
print("Ben's birthday is on",birthday2)
print("Rishi's birthday is on",birthday3)